### ISSUE TITLE
`Resource not found in cluster: apiextensions.k8s.io/v1/CustomResourceDefinition:mariadbs.k8s.mariadb.com`

### ISSUE THREAD

**Issue by plsnotracking** [mariadb-operator/mariadb-operator-helm#12]
I used `ArgoCD`, and I tried to deploy the `mariadb-operator`, but I constantly run into an issue

`Resource not found in cluster: [apiextensions.k8s.io/v1/CustomResourceDefinition:mariadbs.k8s.mariadb.com](http://apiextensions.k8s.io/v1/CustomResourceDefinition:mariadbs.k8s.mariadb.com)`

My ArgoCD configuration
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator
  namespace: argocd
spec:
  destination:
    namespace: mariadb-operator
    name: enterprise
  project: staging
  sources:
    # Chart from Chart Repo
    - chart: mariadb-operator
      repoURL: https://mariadb-operator.github.io/mariadb-operator
      targetRevision: 0.27.0
      helm:
        valueFiles:
        - $values/enterprise/mariadb-operator/values.yaml
    # Values from Git
    - repoURL: 'https://link/to/git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

I'm using `0.27.0` and do not pass any other values in `values.yaml`

Thanks.
